# Project: tetris
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = tetris_private.res
OBJ  = src/main.o src/tetris.o src/util.o $(RES)
LINKOBJ  = src/main.o src/tetris.o src/util.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/Dev-Cpp/SDL/SDL-1.2.14/lib" -L"C:/Dev-Cpp/SDL/SDL_image-1.2.10/lib" -L"C:/Dev-Cpp/SDL/SDL_ttf-2.0.10/lib" -mwindows -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_ttf  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/SDL/SDL-1.2.14/include"  -I"C:/Dev-Cpp/SDL/SDL_image-1.2.10/include"  -I"C:/Dev-Cpp/SDL/SDL_ttf-2.0.10/include" 
BIN  = tetris.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before tetris.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "tetris.exe" $(LIBS)

src/main.o: src/main.cpp
	$(CPP) -c src/main.cpp -o src/main.o $(CXXFLAGS)

src/tetris.o: src/tetris.cpp
	$(CPP) -c src/tetris.cpp -o src/tetris.o $(CXXFLAGS)

src/util.o: src/util.cpp
	$(CPP) -c src/util.cpp -o src/util.o $(CXXFLAGS)

tetris_private.res: tetris_private.rc 
	$(WINDRES) -i tetris_private.rc --input-format=rc -o tetris_private.res -O coff 
